# Generated by Django 5.0.2 on 2024-02-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desktop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="profileimg",
            field=models.ImageField(default="team1.png", upload_to="profile_images/"),
        ),
    ]
